  `id` int(10) unsigned NOT NULL auto_increment,
  `media` enum('bin','image','icon','audio','video','document','executable','text','archive') default 'bin',
  `parent` int(10) unsigned NOT NULL default '0',
  `preview` int(10) unsigned NOT NULL default '0',
  `icon` int(10) unsigned NOT NULL default '0',
  `author` int(10) unsigned NOT NULL default '0',
  `size` int(10) unsigned NOT NULL default '0',
  `posted` datetime NOT NULL default '2010-01-01 10:01:01',
  `mime` varchar(64) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `title` text  NOT NULL,
  `description` text  NOT NULL,
  `keywords` text  NOT NULL,
  `md5` varchar(32) NOT NULL,
  `height` int(10) unsigned NOT NULL default '0',
  `width` int(10) unsigned NOT NULL default '0',
  `bitrate` int(10) unsigned NOT NULL default '128',
  `framerate` int(10) unsigned NOT NULL default '25',
  `samplingrate` varchar(6) NOT NULL default '0',
  `channels` int(10) unsigned NOT NULL default '1',
  `duration` int(10) unsigned NOT NULL default '0',

  PRIMARY KEY  (`id`),
  KEY `media` (`media`),
  KEY `posted` (`posted`),
  KEY `author` (`author`),
  KEY `parent` (`parent`),
  KEY `preview` (`preview`)