  `id` int(10) unsigned NOT NULL auto_increment,
  `idurl` int(10) unsigned NOT NULL default '0',
  `parent` int(10) unsigned NOT NULL default '0',
  `author` int(10) unsigned NOT NULL default '0',
  `icon` int(10) unsigned NOT NULL default '0',
  `posted` datetime NOT NULL default '2010-01-01 10:01:01',
  `title` text NOT NULL,
  `title2` text NOT NULL,
  `filtered` longtext NOT NULL,
  `excerpt` text NOT NULL,
  `rss` text NOT NULL,
  `description` text NOT NULL,
  `moretitle` varchar(255) NOT NULL,
  `categories` text NOT NULL,
  `tags` text NOT NULL,
  `files` text NOT NULL,
  `password` varchar(64) NOT NULL,
  `theme` varchar(64) NOT NULL,
  `tmlfile` varchar(64) NOT NULL,
  `status` enum('published','draft','future','deleted') default 'published',
  `commentsenabled` boolean default true,
  `pingenabled` boolean default true,
  `commentscount` int(10) unsigned NOT NULL default '0',
  `pingbackscount` int(10) unsigned NOT NULL default '0',
  `pagescount` int(10) unsigned NOT NULL default '0',

  PRIMARY KEY  (`id`),
  KEY `posted` (`posted`),
  KEY `status` (`status`),
  KEY `parent` (`parent`)