  `id` int(10) unsigned NOT NULL default '0',
  `type` enum('bug','feature','support','task') NOT NULL default 'bug',
  `state` enum('fixed','opened','wontfix','invalid','duplicate','reassign') default 'opened',
  `prio` enum('trivial','minor','major','critical','blocker') default 'major',
  `assignto` int(10) unsigned NOT NULL default '0',
  `closed` datetime NOT NULL default '2010-01-01 10:01:01',
  `version` varchar(5) NOT NULL,
  `votes` int(10) unsigned NOT NULL default '0',
  `poll` int(10) unsigned NOT NULL default '0',
  `os` varchar(32) NOT NULL,
  `reproduced` tinyint(1) default '0',
  `code` longtext NOT NULL,

  PRIMARY KEY  (`id`,`type`),
  KEY `state` (`state`),
  KEY `prio` (`prio`)