  id int unsigned NOT NULL auto_increment,
  media enum('bin','image','icon','audio','video','document','executable','text','archive') default 'bin',
  parent int unsigned NOT NULL default '0',
  preview int unsigned NOT NULL default '0',
  icon int unsigned NOT NULL default '0',
  author int unsigned NOT NULL default '0',
idperm int unsigned NOT NULL default '0',
  height int unsigned NOT NULL default '0',
  width int unsigned NOT NULL default '0',
  size int unsigned NOT NULL default '0',
  posted datetime NOT NULL default '2010-01-01 10:01:01',
  hash char(22) NOT NULL,
  mime varchar(64) NOT NULL,
  filename varchar(255) NOT NULL,
  title text  NOT NULL,
  description text  NOT NULL,
  keywords text  NOT NULL,

  PRIMARY KEY  (id),
  KEY preview (preview),
 KEY author (author),
  KEY parent (parent),
  KEY media (media),
  KEY posted (posted)
