id int UNSIGNED NOT NULL auto_increment,
mediatype enum('bin', 'image', 'audio', 'video') default 'bin',
parent int UNSIGNED NOT NULL default 0,
preview int UNSIGNED NOT NULL default 0,
icon int UNSIGNED NOT NULL default 0,
author int UNSIGNED NOT NULL default 0,
posted datetime NOT NULL default '2010-01-01 10:01:01',
itemscount  int UNSIGNED NOT NULL default 0,
filename varchar(255) not null,
title varchar(255) not null,
description varchar(255) not null,
keywords varchar(255) not null,

     PRIMARY KEY(id),
key posted (posted),
key author(author)
key mediatype(mediatype),
key parent (parent),
key preview (preview),

